-- Create categories table
CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,   -- Auto-incrementing ID
    name VARCHAR(255) NOT NULL,                                -- Category name
    description TEXT,                                         -- Category description
    prefix VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,           -- Created timestamp (from BaseEntity)
    created_by VARCHAR(255),                                   -- Created by user (from BaseEntity)
    updated_at TIMESTAMP,                                      -- Last updated timestamp (from BaseEntity)
    updated_by VARCHAR(255)                                    -- Updated by user (from BaseEntity)
);

-- Create suppliers table
CREATE TABLE suppliers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,   -- Auto-incrementing ID
    name VARCHAR(255) NOT NULL,                                -- Supplier name
    contact_info TEXT,                                        -- Supplier contact information
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,           -- Created timestamp (from BaseEntity)
    created_by VARCHAR(255),                                   -- Created by user (from BaseEntity)
    updated_at TIMESTAMP,                                      -- Last updated timestamp (from BaseEntity)
    updated_by VARCHAR(255)                                    -- Updated by user (from BaseEntity)
);

-- Create the product_category join table for many-to-many relationship
CREATE TABLE product_category (
    product_id BIGINT NOT NULL,                      -- Foreign key to products
    category_id BIGINT NOT NULL,                     -- Foreign key to categories
    PRIMARY KEY (product_id, category_id),           -- Composite primary key
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,  -- Foreign key to products
    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE  -- Foreign key to categories
);

