CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,   -- Unique ID for the payment transaction
    order_id BIGINT NOT NULL,                                 -- Foreign key linking to the orders table

    amount DECIMAL(10, 2) NOT NULL,                           -- The amount for this specific transaction (can be negative for refunds)
    payment_method VARCHAR(50) NOT NULL,                      -- e.g., 'CREDIT_CARD', 'COD', 'MOMO', 'BANK_TRANSFER'
    status VARCHAR(50) NOT NULL,                              -- The status of THIS transaction: PENDING, PAID, FAILED, REFUNDED

    gateway_transaction_id VARCHAR(255),                      -- The unique ID from the payment provider (Stripe, MoMo, etc.). Can be null for COD.

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_at TIMESTAMP,
    updated_by VARCHAR(255),
    is_deleted BOOLEAN DEFAULT FALSE,
    deleted_at TIMESTAMP,

    -- Foreign key constraint
    CONSTRAINT fk_payment_order FOREIGN KEY (order_id) REFERENCES orders(id)
);
