spring.application.name=payment-service

stripe.webhook.secret=
stripe.secret.key=
stripe.publishable.key=

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest