spring.application.name=ordersystem


# Stripe API Keys (Use your test keys for development)
stripe.secret.key=sk_test_
stripe.publishable.key=pk_test_

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

rabbitmq.exchange.name=payment.exchange
rabbitmq.queue.succeeded=payment.succeeded.queue
rabbitmq.queue.failed=payment.failed.queue
rabbitmq.routingkey.succeeded=payment.succeeded.routingkey
rabbitmq.routingkey.failed=payment.failed.routingkey