spring.application.name=ordersystem


# Stripe API Keys (Use your test keys for development)
stripe.secret.key=sk_test_
stripe.publishable.key=pk_test_
# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
